spring:
  application:
    name: blog-platform-api

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: admin1234
    url: jdbc:postgresql://localhost:5432/blog-db

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mvc:
    problemdetails:
      enabled: true

  flyway:
    enabled: false

server:
  port: 8080

logging:
  level:
    com.example.blog_platform_api: DEBUG
    org.springframework.security: INFO

security:
  jwt:
    secret-key: dGhpcyBpcyBhIHN1cGVyIHNlY3JldCBrZXkgZm9yIGJsb2cgcGxhdGZvcm0gand0IDI1NiBiaXRz   # Base64-encoded 256-bit key for HS256.
    expiration: 86400000  # 24 hours in milliseconds

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html